Repository yunnsbz/File-Manager, pull requests merged in 2025-04, with the labels that each got.

#1 Refactoring
  CMakeLists.txt
  TabManager.cpp
  TabManager.h
  mainwindow.cpp
  mainwindow.hpp
Labels: bug, good first issue

#7 Merging Toolbar Feature I
  CMakeLists.txt
  TabManager.cpp
  TabManager.h
  ToolBarManager.cpp
  ToolBarManager.h
  img/arrow-left-white.svg
  img/arrow-left.svg
  img/arrow-right-white.svg
  img/arrow-right.svg
  main.cpp
  mainwindow.cpp
  mainwindow.hpp
  mainwindow.ui
  resources.qrc
  styles/style.qss
Labels: enhancement

#12 Feature dual pane and column view
  FileModelOperations.cpp
  FileModelOperations.h
  TabManager.cpp
  TabManager.h
  TableManager.cpp
  TableManager.h
  TreeManager.cpp
  TreeManager.h
  mainwindow.cpp
  mainwindow.hpp
  mainwindow.ui
Labels: enhancement

#17 fixed clang build
  CMakeLists.txt
  TabManager.cpp
  TabManager.h
  TableManager.cpp
  TableManager.h
  ToolBarManager.cpp
  ToolBarManager.h
  TreeManager.cpp
  TreeManager.h
  mainwindow.cpp
  mainwindow.hpp
Labels: bug, code cleanup
